apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-ssl-secret
spec:
  params:
    - name: nameOfCluster
      description: Name of cluster to deploy image to
    - name: clusterRegion
      description: Region where cluster is located
    - name: apiUrl
      description: API URL for interacting with IBM Cloud
  steps:
    - name: create-secret
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: apiKey
        - name: CERTIFCATE
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: postgresCertificate
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $(params.apiUrl) -r $(params.clusterRegion);
          export IKS_BETA_VERSION=1;
          touch root.crt;
          echo $CERTIFCATE >> root.crt;
          ibmcloud ks cluster config -c $(params.nameOfCluster);
          kubectl -n default create secret generic postgres-cert --from-file=root.crt;