apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-image-to-ibm-cloud
spec:
  resources:
    inputs:
      - name: git-repo
        type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToDeploymentFile
      description: The path to the yaml file to deploy within the git source
      default: deploy.yaml
    - name: nameOfCluster
      description: Name of cluster to deploy image to
    - name: containerRepoUrl
      description: Base url to the container repo
    - name: containerRepoNamespace
      description: Namespace image is being stored under
    - name: deploymentImage
      description: Name of image to be deployed
    - name: imageTag
      description: Tag to apply to the built image
    - name: clusterRegion
      description: Region where cluster is located
    - name: apiUrl
      description: API URL for interacting with IBM Cloud
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;IMAGE;$(params.containerRepoUrl)/$(params.containerRepoNamespace)/$(params.deploymentImage):$(params.imageTag);g"
        - "$(resources.inputs.git-repo.path)/$(params.pathToContext)/$(params.pathToDeploymentFile)"
    - name: deploy-app
      image: ibmcom/pipeline-base-image
      env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: apiKey
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $(params.apiUrl) -r $(params.clusterRegion) --apikey $APIKEY;
          export IKS_BETA_VERSION=1;
          ibmcloud ks cluster config -c $(params.nameOfCluster);
          kubectl apply -f $(resources.inputs.git-repo.path)/$(params.pathToContext)/$(params.pathToDeploymentFile)