apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-push-event-listener
spec:
  serviceAccountName: service-account
  triggers:
  - name: pullrequest-build-and-deploy
    template:
      name: ibm-cloud-trigger-template
    bindings:
    - name: gitlab-trigger-binding