apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sampleapp-build-and-deploy
spec:
  params:
  - name: URL
    value: $(body.repository.clone_url)
  - name: REVISION
    value: $(body.pull_request.head.sha)
  - name: NAMESPACE
    value: living-on-the-cloud
  - name: DEPLOYMENT
    value: sampleapp
  - name: SERVICE_ACCOUNT
    value: service-account