apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ibm-cloud-trigger-template
spec:
  params:
  - name: path-to-context
    description: The path to the build context, used by Kaniko
    default: .
  - name: path-to-deployment-file
    description: The path to the yaml file describe how to deploy the application. 
    default: deployment.yaml
  - name: path-to-dockerfile
    description: The path to the docker image build file
    default: Dockerfile
  - name: api-url
    description: The api url for interacting with ibm cloud
    default: cloud.ibm.com
  - name: container-repo-url
    description: Base url for container repository
    default: us.icr.io
  - name: container-repo-namespace
    description: Namespace where image is located
  - name: deployment-image
    description: Name of image to be deployed
  - name: name-of-cluster
    description: The number of cluster to deploy the image to
  - name: cluster-region
    description: The region where the cluster resides
    default: us-south
  - name: git-repo-url
    description: URL to the git repo to be cloned
  - name: commit-id
    description: The revision to build and deploy.
  - name: git-access-token
    description: The service account id the pipeline is run under
  - name: apikey
    description: Service Account API KEY for interacting with IBM Cloud note the specific syntax of apikey has special relevance to many IBM Cloud resources, so should not be changed.
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-pipeline-
    spec:
      serviceAccountName: service-account
      pipelineRef:
        name: build-pipeline
      params:
      - name: path-to-context
        value: $(params.path-to-context)
      - name: path-to-deployment-file
        value: $(params.path-to-deployment-file)
      - name: path-to-dockerfile
        value: $(params.path-to-dockerfile)
      - name: api-url
        value: $(params.api-url)
      - name: container-repo-url
        value: $(params.container-repo-url)
      - name: container-repo-namespace
        value: $(params.container-repo-namespace)
      - name: deployment-image
        value: $(params.deployment-image)
      - name: name-of-cluster
        value: $(params.name-of-cluster)
      - name: cluster-region
        value: $(params.cluster-region)
      - name: git-access-token
        value: $(params.git-access-token)
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: commit-id
        value: $(params.commit-id)
      workspaces:
        - name: git-repo
          persistentVolumeClaim:
            claimName: $(uid)-pvc
  - apiVersion: v1
    stringData:
      username: iamapikey
      password: $(params.apikey)
    kind: Secret
    type: kubernetes.io/basic-auth
    metadata:
      name: ibm-cr-secret
      annotations:
        tekton.dev/docker-0: $(params.container-repo-url)
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: $(uid)-pvc
    spec:
      resources:
        requests:
          storage: 5Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce