apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sampleapp-build-and-deploy
spec:
  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision to build and deploy.
  - name: NAMESPACE
    description: The namespace is used by OpenShift's internal image registry to store the built image.
  - name: DEPLOYMENT
    description: Name of the Deployment and the container name in the Deployment.
  - name: SERVICE_ACCOUNT
    description: The ServiceAccount under which to run the Pipeline.
  - name: API-KEY
    description: The API-KEY
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: sample-build-and-deploy-
    spec:
      serviceAccountName: $(params.SERVICE_ACCOUNT)
      pipelineRef:
        name: application-pipeline
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.REVISION)
          - name: url
            value: $(params.URL)
      params:
      - name: DEPLOYMENT
        value: $(params.DEPLOYMENT)
  - apiVersion: v1
    stringData:
      username: iamapikey
      password: $(params.API-KEY)
    kind: Secret
    type: kubernetes.io/basic-auth
    metadata:
      name: ibm-cr-secret
      annotations:
        tekton.dev/docker-0: us.icr.io
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pipelinerun-$(uid)-pvc
    spec:
      resources:
        requests:
          storage:  5Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce