apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ibm-cloud-trigger-template
spec:
  params:
  - name: pipelineName
    description: The name of the pipeline to be executed
    default: storm-tracker-application-pipeline
  - name: pathToContext
    description: The path to the build context, used by Kaniko - within the workspace
    default: .
  - name: pathToDeploymentFile
    description: The path to the yaml file describe how to deploy the application. 
    default: deployment.yaml
  - name: pathToDockerfile
    description: The path to the docker image build file
    default: Dockerfile
  - name: apiUrl
    description: The api url for interacting with ibm cloud
    default: cloud.ibm.com
  - name: containerRepoUrl
    description: Base url for container repository
  - name: containerRepoNamespace
    description: Namespace where image is located
  - name: deploymentImage
    description: Name of image to be deployed
  - name: imageTag
    description: Tag of image to be deployed
  - name: nameOfCluster
    description: The number of cluster to deploy the image to
  - name: clusterRegion
    description: The region where the cluster resides
  - name: mvnGoals
    description: The Maven goal(s) to run
    type: array
    default: ["package"]
  - name: gitRepoUrl
    description: The git repo url to the repository of the application that is being built.
  - name: commitId
    description: The revision to build and deploy.
  - name: serviceAccountId
    description: The service account id the pipeline is run under
  - name: apiKey
    description: Service Account API KEY for interacting with IBM Cloud
  - name: gitUser
    description: The revision to build and deploy.
  - name: gitApiKey
    description: The service account id the pipeline is run under
  - name: gitUrl
    description: Service Account API KEY for interacting with IBM Cloud
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(params.deploymentImage)-build-
    spec:
      serviceAccountName: $(params.serviceAccountId)
      pipelineRef:
        name: storm-tracker-application-pipeline
      resources:
      - name: git-repo
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.commitId)
          - name: url
            value: $(params.gitRepoUrl)
  - apiVersion: v1
    stringData:
      username: iamapikey
      password: $(params.apiKey)
    kind: Secret
    type: kubernetes.io/basic-auth
    metadata:
      name: ibm-cr-secret
      annotations:
        tekton.dev/docker-0: $(params.containerRepoUrl)
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/basic-auth
    metadata:
      name: gitlab-secret
      annotations:
        tekton.dev/git-0: $(params.gitUrl)
    stringData:
      username: $(params.gitUser)
      password: $(params.gitApiKey)