apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment-yaml
spec:
  params:
    - name: path-to-context
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: path-to-deployment-file
      description: The path to the yaml file to deploy within the git source
      default: deployment.yaml
    - name: placeholder-name
      description: Placeholder in yaml file that is too be replaced
    - name: replacement-value
      description: The value that will replace the place holder
  workspaces:
    - name: source
  steps:
    - name: update-yaml
      image: alpine:3.12
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;$(params.placeholder-name);$(params.replacement-value);g"
        - "$(workspaces.source.path)/$(params.path-to-context)/$(params.path-to-deployment-file)"